# Generated by Django 3.2.7 on 2022-10-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
    ]
