# Generated by Django 3.2.7 on 2023-03-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pv',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
